"""SQLAlchemy persistence models."""

from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String, Text, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from timpapers.database import Base


class Author(Base):
    """Tracked author identity."""

    __tablename__ = "authors"

    id: Mapped[int] = mapped_column(primary_key=True)
    full_name: Mapped[str] = mapped_column(String(255), index=True)
    openalex_id: Mapped[str | None] = mapped_column(String(80), unique=True)
    semanticscholar_id: Mapped[str | None] = mapped_column(String(80), unique=True)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    papers: Mapped[list[Paper]] = relationship(back_populates="author", cascade="all, delete-orphan")
    metric_override: Mapped[AuthorMetricOverride | None] = relationship(
        back_populates="author",
        cascade="all, delete-orphan",
        uselist=False,
    )


class AuthorMetricOverride(Base):
    """Optional external metric overrides for one author."""

    __tablename__ = "author_metric_overrides"

    id: Mapped[int] = mapped_column(primary_key=True)
    author_id: Mapped[int] = mapped_column(ForeignKey("authors.id"), unique=True, index=True)
    source: Mapped[str] = mapped_column(String(80), default="Google Scholar")
    h_index: Mapped[int | None] = mapped_column(Integer)
    i10_index: Mapped[int | None] = mapped_column(Integer)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    author: Mapped[Author] = relationship(back_populates="metric_override")


class Paper(Base):
    """Persisted publication metadata and latest citation count."""

    __tablename__ = "papers"
    __table_args__ = (UniqueConstraint("author_id", "openalex_work_id", name="uq_author_work"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    author_id: Mapped[int] = mapped_column(ForeignKey("authors.id"), index=True)
    title: Mapped[str] = mapped_column(Text)
    year: Mapped[int | None] = mapped_column(Integer)
    doi: Mapped[str | None] = mapped_column(String(255), index=True)
    venue: Mapped[str | None] = mapped_column(String(255))
    author_list: Mapped[str] = mapped_column(Text, default="")
    openalex_work_id: Mapped[str] = mapped_column(String(80), index=True)
    semanticscholar_paper_id: Mapped[str | None] = mapped_column(String(80), index=True)
    citation_count: Mapped[int] = mapped_column(Integer, default=0)
    first_seen_citation_count: Mapped[int] = mapped_column(Integer, default=0)
    last_seen_citation_count: Mapped[int] = mapped_column(Integer, default=0)
    last_updated: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    author: Mapped[Author] = relationship(back_populates="papers")
    snapshots: Mapped[list[CitationSnapshot]] = relationship(back_populates="paper", cascade="all, delete-orphan")


class CitationSnapshot(Base):
    """Time-series citation snapshot for each paper."""

    __tablename__ = "citation_snapshots"

    id: Mapped[int] = mapped_column(primary_key=True)
    paper_id: Mapped[int] = mapped_column(ForeignKey("papers.id"), index=True)
    citation_count: Mapped[int] = mapped_column(Integer)
    captured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), index=True)

    paper: Mapped[Paper] = relationship(back_populates="snapshots")


class MetricSnapshot(Base):
    """Historic computed metric snapshot for charting and trend analysis."""

    __tablename__ = "metric_snapshots"

    id: Mapped[int] = mapped_column(primary_key=True)
    author_id: Mapped[int] = mapped_column(ForeignKey("authors.id"), index=True)
    total_citations: Mapped[int] = mapped_column(Integer)
    h_index: Mapped[int] = mapped_column(Integer)
    i10_index: Mapped[int] = mapped_column(Integer)
    paper_count: Mapped[int] = mapped_column(Integer)
    captured_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), index=True)


class Event(Base):
    """Alerts/events generated by metric and citation threshold changes."""

    __tablename__ = "events"

    id: Mapped[int] = mapped_column(primary_key=True)
    author_id: Mapped[int] = mapped_column(ForeignKey("authors.id"), index=True)
    event_type: Mapped[str] = mapped_column(String(50), index=True)
    message: Mapped[str] = mapped_column(Text)
    paper_id: Mapped[int | None] = mapped_column(ForeignKey("papers.id"), index=True)
    event_value: Mapped[float | None] = mapped_column(Float)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), index=True)
